name: fish
channels:
  - defaults
dependencies:
  - scikit-learn
  - opencv
  - python
  - black
  - ipython
  - pip
  - memory_profiler
  - scikit-image
  - line_profiler
  - jupyterlab
  - bokeh
  - tqdm
